---
title: "landUseChanges"
author: "Andres, Raquel, Mauricio"
date: "7/25/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(raster)
#read alrge scale
LU_2014<-raster('~/landuse_disease/Rasterall/ACRE_2014/AC_2014_RASTER.tif')
LU_2004<-raster('~/landuse_disease/Rasterall/ACRE_2004/AC_2004_RASTER.tif')
#read study area
#LUSA<-raster('~/landuse_disease/Raster/ComposicaoBuffer500m_TC14.tif')
#change projection
#LUSA_ll<-projectRaster(from =LUSA,to =LU_2014)
e <- extent(-75, -71, -9, -7)
LU_2014_SA=crop(LU_2014,e)
LU_2004_SA=crop(LU_2004,e)
```



```{r}
f04<-freq(LU_2004_SA)
f14<-freq(LU_2014_SA)
f04=as.data.frame(f04)
f14=as.data.frame(f14)

dat_LU14<-as.data.frame(LU_2014_SA@data@attributes) 
dat_LU04<-as.data.frame(LU_2004_SA@data@attributes)

f04$value %in% f14$value
m_tableLUchange<-merge(dat_LU14,dat_LU04,by="color")

```

```{r}
barplot(height = (m_tableLUchange$Count.x-m_tableLUchange$Count.y)/(m_tableLUchange$Count.x+m_tableLUchange$Count.y),names.arg=m_tableLUchange$tc_2014,cex.name=0.4,las=2)


```


##RECLASIFICATION
```{r}
#Others 18
#pastos 19
#regeneration 20
#forest 21
#Urban 22
#Mix 23
#Agriculture 24
#deforested 25
#mining 26

names_LUtypes=c(
  "Others",
  "Pastos",
  "Regeneration",
  "Forest" ,
  "Urban" ,
  "Mixed",
  "Agriculture", 
  "deforested",
  "mining")
rc_v_2014=c(1,18,
       2,19,
       3,20,  #check if deforestation is it own class
       4,23,
       5,19,
       6,19,
       7,22,
       8,18,
       9,21,
       10,24,
       11,19,
       12,25,
       13,26,
       14,20,
       15,18)


rc_v_2004=c(1,18,
       2,22,
       3,25,  #check if deforestation is it own class
       4,21,
       5,18,
       6,23,
       7,18,
       8,18,
       9,19,
       10,19,
       11,19,
       12,20,
       13,20)




reclass_matrix_2014=matrix(rc_v_2014, ncol=2, byrow=TRUE)
reclass_matrix_2004=matrix(rc_v_2004, ncol=2, byrow=TRUE)
LU_rc2004 <- reclassify(LU_2004_SA, reclass_matrix)
LU_rc2014 <- reclassify(LU_2014_SA, reclass_matrix)
```

#create the tranissiton matrix
```{r}
Matrix_transitions=matrix(ncol=9,nrow=9)
colnames(Matrix_transitions)<-names_LUtypes
rownames(Matrix_transitions)<-colnames(Matrix_transitions)
for (i in 18:26){
  for (j in 18:26){
    if(j!=i){  
        antes=(LU_rc2004==i)
        despues=(LU_rc2014==j)
        differencia=(antes - despues)
        temp_im=(antes +(differencia==0))
        ff_before=as.data.frame(freq(antes))  
        ff_after<-as.data.frame(freq(temp_im))
        if(length(which(ff_after$value==2))!=0){
          Matrix_transitions[(i-17),(j-17)]<-ff_after$count[which(ff_after$value==2)]/ff_before$count[which(ff_before$value==1)]
        }
        else{
          Matrix_transitions[(i-17),(j-17)]<-0
        }
    }
    else{
      Matrix_transitions[(i-17),(j-17)]=NA
    }
    print(c(i,j))  
    print(Matrix_transitions)
}
  
}

saveRDS(Matrix_transitions,file = "transition_matrix" )
lattice::levelplot(Matrix_transitions)
```